schemaVersion: 2.1.0
metadata:
  name: java-maven-quarkus-lombok
components:
  - name: tools
    container:
      args:
        - sh
        - '-c'
        - '${PLUGIN_REMOTE_ENDPOINT_EXECUTABLE}'
      endpoints:
        - exposure: none
          name: debug
          protocol: tcp
          targetPort: 5005
        - exposure: public
          name: blog-posts-endpoint
          path: /blog/posts
          protocol: http
          targetPort: 8080
      env:
        - name: QUARKUS_HTTP_HOST
          value: 0.0.0.0
        - name: PLUGIN_REMOTE_ENDPOINT_EXECUTABLE
          value: /remote-endpoint/plugin-remote-endpoint
      image: 'registry.redhat.io/devspaces/udi-rhel8'
      memoryLimit: 4G
      mountSources: true
      sourceMapping: /projects
      volumeMounts:
        - name: m2
          path: /home/user/.m2
        - name: remote-endpoint
          path: /remote-endpoint
        - name: plugins
          path: /plugins
  - name: m2
    volume:
      size: 1G